### Step 1: Importing Neccessary Dependencies

In [2]:
import numpy as np

###  Step 2: Input Preparation

In [3]:
input_map = np.array([
    [ 1,  3,  2,  4,  1,  0],
    [ 5,  6,  1,  2,  3,  2],
    [ 3,  2,  7,  8,  1,  4],
    [ 1,  0,  3,  6,  2,  5],
    [ 4,  5,  1,  2,  9,  3],
    [ 2,  1,  3,  4,  6,  8]
])

print("=== INPUT FEATURE MAP ===")
print(input_map)
print(f"\nInput shape : {input_map.shape}")

=== INPUT FEATURE MAP ===
[[1 3 2 4 1 0]
 [5 6 1 2 3 2]
 [3 2 7 8 1 4]
 [1 0 3 6 2 5]
 [4 5 1 2 9 3]
 [2 1 3 4 6 8]]

Input shape : (6, 6)


### Step 3: Pooling Setup

In [4]:
pool_size = 2
stride    = 2

In [5]:
input_h, input_w = input_map.shape
output_h = (input_h - pool_size) // stride + 1
output_w = (input_w - pool_size) // stride + 1

In [6]:
print(f"Pool size   : {pool_size}×{pool_size}")
print(f"Stride      : {stride}")
print(f"Output size : {output_h}×{output_w}")

Pool size   : 2×2
Stride      : 2
Output size : 3×3


In [8]:
# Pre-allocating the output matrix with zeros
output_map = np.zeros((output_h, output_w), dtype=input_map.dtype)

### Step 4 & 5: Pooling Loop + Reconstruction

In [9]:
for i in range(output_h):
    for j in range(output_w):

        # Computing the top-left corner of the current 2×2 block
        row_start = i * stride
        col_start = j * stride

        # Slicing out the 2×2 block from the input feature map
        block = input_map[row_start : row_start + pool_size,
                          col_start : col_start + pool_size]

        # Appling max pooling: take the single highest value in the block
        output_map[i, j] = np.max(block)

        print(f"Block [{i},{j}]  rows {row_start}:{row_start+pool_size}"
              f"  cols {col_start}:{col_start+pool_size}")
        print(block)
        print(f"  → max = {output_map[i, j]}\n")

Block [0,0]  rows 0:2  cols 0:2
[[1 3]
 [5 6]]
  → max = 6

Block [0,1]  rows 0:2  cols 2:4
[[2 4]
 [1 2]]
  → max = 4

Block [0,2]  rows 0:2  cols 4:6
[[1 0]
 [3 2]]
  → max = 3

Block [1,0]  rows 2:4  cols 0:2
[[3 2]
 [1 0]]
  → max = 3

Block [1,1]  rows 2:4  cols 2:4
[[7 8]
 [3 6]]
  → max = 8

Block [1,2]  rows 2:4  cols 4:6
[[1 4]
 [2 5]]
  → max = 5

Block [2,0]  rows 4:6  cols 0:2
[[4 5]
 [2 1]]
  → max = 5

Block [2,1]  rows 4:6  cols 2:4
[[1 2]
 [3 4]]
  → max = 4

Block [2,2]  rows 4:6  cols 4:6
[[9 3]
 [6 8]]
  → max = 9



### Step 6: Final Output

In [10]:
print("=== OUTPUT FEATURE MAP (after 2×2 Max Pooling) ===")
print(output_map)
print(f"\nInput  shape : {input_map.shape}")
print(f"Output shape : {output_map.shape}")
print(f"Size reduced by factor : {input_map.size // output_map.size}×")

=== OUTPUT FEATURE MAP (after 2×2 Max Pooling) ===
[[6 4 3]
 [3 8 5]
 [5 4 9]]

Input  shape : (6, 6)
Output shape : (3, 3)
Size reduced by factor : 4×


### Reusable Function

In [15]:
def max_pool2d(feature_map: np.ndarray, pool_size: int = 2, stride: int = 2):
    h, w = feature_map.shape
    out_h = (h - pool_size) // stride + 1
    out_w = (w - pool_size) // stride + 1
    output = np.zeros((out_h, out_w), dtype=feature_map.dtype)

    for i in range(out_h):
        for j in range(out_w):
            r, c = i * stride, j * stride
            output[i, j] = np.max(
                feature_map[r:r + pool_size, c:c + pool_size]
            )
    return output

In [16]:
# Smoke test on a random 8×8 map
np.random.seed(42)
test_map = np.random.randint(0, 100, size=(8, 8))
print("Random 8×8 input:\n", test_map)
print("\nPooled output:\n", max_pool2d(test_map))

Random 8×8 input:
 [[51 92 14 71 60 20 82 86]
 [74 74 87 99 23  2 21 52]
 [ 1 87 29 37  1 63 59 20]
 [32 75 57 21 88 48 90 58]
 [41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20]
 [72 38 17  3 88 59 13  8]
 [89 52  1 83 91 59 70 43]]

Pooled output:
 [[92 99 60 86]
 [87 57 88 90]
 [91 79 61 61]
 [89 83 91 70]]
